language: java

os:
  - linux
  - osx

addons:
  homebrew:
    brewfile: true
    update: true
  apt:
    sources:
      - sourceline: ppa:cleishm/neo4j
    packages:
      - cypher-lint
      - libcypher-parser-dev

script:
  - cypher-lint < import.cyp
  - mvn package